//import
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import javax.swing.JOptionPane;

//==================================================================================================
public class food_drinks extends javax.swing.JFrame {
    //initializing variables
    double Chips = 100;
    double Chicken = 120;
    double Spaghetti = 90;
    double Beef  = 150;
    double coke = 50;
    double fanta = 50;
    double sprite = 50;
    double stoney = 50;
    
//==================================================================================================    
    public food_drinks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //our own closing method
     private void systemExit(){
        WindowEvent winclosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jQty1 = new javax.swing.JTextField();
        jQty2 = new javax.swing.JTextField();
        jQty3 = new javax.swing.JTextField();
        jQty4 = new javax.swing.JTextField();
        jQty6 = new javax.swing.JTextField();
        jQty7 = new javax.swing.JTextField();
        jQty8 = new javax.swing.JTextField();
        jQty9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        foodcost = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        drinkscost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jBalance = new javax.swing.JTextField();
        jTotal = new javax.swing.JTextField();
        BtnReset = new javax.swing.JButton();
        BtnOrder = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Price1 = new javax.swing.JTextField();
        Price2 = new javax.swing.JTextField();
        Price3 = new javax.swing.JTextField();
        Price4 = new javax.swing.JTextField();
        BtnExit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Price6 = new javax.swing.JTextField();
        Price7 = new javax.swing.JTextField();
        Price8 = new javax.swing.JTextField();
        Price9 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BtnReceipt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOOD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DRINKS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Quantity");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBox1.setText("Chips");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBox2.setText("Chicken");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBox3.setText("Spaghetti");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBox4.setText("Beef");
        jCheckBox4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBox5.setText("Coke");
        jCheckBox5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBox6.setText("Fanta");
        jCheckBox6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBox7.setText("Sprite");
        jCheckBox7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBox8.setText("Stoney");
        jCheckBox8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Quantity");

        jQty1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jQty1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jQty1.setText("0");
        jQty1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jQty1.setEnabled(false);
        jQty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQty1ActionPerformed(evt);
            }
        });
        jQty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jQty1KeyTyped(evt);
            }
        });

        jQty2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jQty2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jQty2.setText("0");
        jQty2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jQty2.setEnabled(false);
        jQty2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jQty2KeyTyped(evt);
            }
        });

        jQty3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jQty3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jQty3.setText("0");
        jQty3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jQty3.setEnabled(false);
        jQty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQty3ActionPerformed(evt);
            }
        });
        jQty3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jQty3KeyTyped(evt);
            }
        });

        jQty4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jQty4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jQty4.setText("0");
        jQty4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jQty4.setEnabled(false);
        jQty4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jQty4KeyTyped(evt);
            }
        });

        jQty6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jQty6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jQty6.setText("0");
        jQty6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jQty6.setEnabled(false);
        jQty6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jQty6KeyTyped(evt);
            }
        });

        jQty7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jQty7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jQty7.setText("0");
        jQty7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jQty7.setEnabled(false);
        jQty7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jQty7KeyTyped(evt);
            }
        });

        jQty8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jQty8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jQty8.setText("0");
        jQty8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jQty8.setEnabled(false);
        jQty8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jQty8KeyTyped(evt);
            }
        });

        jQty9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jQty9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jQty9.setText("0");
        jQty9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jQty9.setEnabled(false);
        jQty9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jQty9KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Cost of Food");

        foodcost.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        foodcost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        foodcost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        foodcost.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        foodcost.setEnabled(false);
        foodcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodcostActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Cost of Drinks");

        drinkscost.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        drinkscost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        drinkscost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        drinkscost.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        drinkscost.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("BALANCE");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("TOTAL");

        jBalance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jBalance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jBalance.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jBalance.setEnabled(false);
        jBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBalanceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBalanceMousePressed(evt);
            }
        });

        jTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTotal.setEnabled(false);
        jTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalActionPerformed(evt);
            }
        });

        BtnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnReset.setText("RESET");
        BtnReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnOrder.setText("ORDER");
        BtnOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BtnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrderActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setText("Price");

        Price1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Price1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Price1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Price1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Price1.setEnabled(false);
        Price1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Price1MouseMoved(evt);
            }
        });
        Price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price1ActionPerformed(evt);
            }
        });

        Price2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Price2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Price2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Price2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Price2.setEnabled(false);
        Price2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Price2MouseMoved(evt);
            }
        });
        Price2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price2ActionPerformed(evt);
            }
        });
        Price2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Price2KeyTyped(evt);
            }
        });

        Price3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Price3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Price3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Price3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Price3.setEnabled(false);
        Price3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Price3MouseMoved(evt);
            }
        });

        Price4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Price4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Price4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Price4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Price4.setEnabled(false);
        Price4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Price4MouseMoved(evt);
            }
        });

        BtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnExit.setText("EXIT");
        BtnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Price");

        Price6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Price6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Price6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Price6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Price6.setEnabled(false);
        Price6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Price6MouseMoved(evt);
            }
        });

        Price7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Price7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Price7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Price7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Price7.setEnabled(false);
        Price7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Price7MouseMoved(evt);
            }
        });

        Price8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Price8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Price8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Price8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Price8.setEnabled(false);
        Price8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Price8MouseMoved(evt);
            }
        });

        Price9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Price9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Price9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Price9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Price9.setEnabled(false);
        Price9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Price9MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                            .addGap(69, 69, 69))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Price1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Price3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Price2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Price4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jQty2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jQty3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jQty4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(56, 56, 56)
                        .addComponent(foodcost, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBox8))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Price8, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                                    .addComponent(Price7)
                                                    .addComponent(Price6)
                                                    .addComponent(Price9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jQty9, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                                    .addComponent(jQty6)
                                                    .addComponent(jQty7, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                                    .addComponent(jQty8)))))
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(54, 54, 54)
                                .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(BtnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drinkscost, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel10))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox1)
                                    .addComponent(Price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox5)
                                    .addComponent(Price6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jQty6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jCheckBox2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Price7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox6)
                                        .addComponent(jQty7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jQty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Price2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jCheckBox7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Price3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox3)
                            .addComponent(jQty3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jQty8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Price8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox4)
                            .addComponent(Price4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jQty4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Price9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox8)
                            .addComponent(jQty9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(foodcost, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(drinkscost, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTotal)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(34, 34, 34))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECEIPT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        BtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnReceipt.setText("PRINT RECEIPT");
        BtnReceipt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReceiptActionPerformed(evt);
            }
        });

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jtxtReceipt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtxtReceipt.setEnabled(false);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(BtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 262, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(23, 23, 23)
                .addComponent(BtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Action performed when button Receipt is pressed
    
    private void BtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReceiptActionPerformed
if (jtxtReceipt == null ){
    
 JOptionPane.showMessageDialog(null, " Nothing to be Printed. \n Please make an order. ", "Strathmore Cafeteria", JOptionPane.OK_OPTION); 
}
else {
   JOptionPane.showMessageDialog(null, "Your receipt has been printed", "Strathmore Cafeteria", JOptionPane.OK_OPTION); 
}

  

// calling the Login JFrame

NewJFrame evans = new NewJFrame();
    evans.setVisible(true);

    }//GEN-LAST:event_BtnReceiptActionPerformed

 //Setting the background color to dark gray
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    
        this.getContentPane().setBackground(Color.DARK_GRAY);        
    }//GEN-LAST:event_formWindowActivated

//Action to be performed when the Reset button is pressed
    
    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
jCheckBox1.setSelected(false);
jCheckBox2.setSelected(false);
jCheckBox3.setSelected(false);
jCheckBox4.setSelected(false);
jCheckBox5.setSelected(false);
jCheckBox6.setSelected(false);
jCheckBox7.setSelected(false);
jCheckBox8.setSelected(false);

jQty1.setText(null);jQty1.setEnabled(false);
jQty2.setText(null);jQty2.setEnabled(false);
jQty3.setText(null);jQty3.setEnabled(false);
jQty4.setText(null);jQty4.setEnabled(false);
jQty6.setText(null);jQty6.setEnabled(false);
jQty7.setText(null);jQty7.setEnabled(false);
jQty8.setText(null);jQty8.setEnabled(false);
jQty9.setText(null);jQty9.setEnabled(false);
jtxtReceipt.setText(null);
foodcost.setText(null);
drinkscost.setText(null);
jBalance.setText(null);
jTotal.setText(null);
Price1.setText(null);
Price2.setText(null);
Price3.setText(null);
Price4.setText(null);
Price6.setText(null);
Price7.setText(null);
Price8.setText(null);
Price9.setText(null);





    }//GEN-LAST:event_BtnResetActionPerformed
//Action performed when the Order button is pressed.
    
    private void BtnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrderActionPerformed


double total,balance,pur1,pur2,pur3,pur4,pur6,pur7,pur8,pur9, Amount;

double Qty1 = Double.parseDouble(jQty1.getText());
double Qty2 = Double.parseDouble(jQty2.getText());
double Qty3 = Double.parseDouble(jQty3.getText());
double Qty4 = Double.parseDouble(jQty4.getText());
double Qty6 = Double.parseDouble(jQty6.getText());
double Qty7 = Double.parseDouble(jQty7.getText());
double Qty8 = Double.parseDouble(jQty8.getText());
double Qty9 = Double.parseDouble(jQty9.getText());


//Setting the prices of food and drinks in the textfields

String chips = String.format("%.2f", Chips);
Price1.setText(chips);

String chicken = String.format("%.2f", Chicken);
Price2.setText(chicken);

String spaghetti = String.format("%.2f", Spaghetti);
Price3.setText(spaghetti);

String beef = String.format("%.2f", Beef);
Price4.setText(beef);

String COKE = String.format("%.2f", coke);
Price6.setText(COKE);

String FANTA = String.format("%.2f", fanta);
Price7.setText(FANTA);

String SPRITE = String.format("%.2f", sprite);
Price8.setText(SPRITE);

String STONEY = String.format("%.2f", stoney);
Price9.setText(STONEY);

// calculation of the price of food * the quantity entered
//..
pur1 =  Qty1 * Chips;
pur2 =  Qty2 * Chicken;
pur3 =  Qty3 * Spaghetti;
pur4 =  Qty4 * Beef;
double pur5 =  pur1+pur2+pur3+pur4;
pur6 = Qty6 * coke;
pur7 = Qty7 * fanta;
pur8 = Qty8 * sprite;
pur9 = Qty9 * stoney;
double pur10 = pur6+pur7+pur8+pur9;
total = pur5 + pur10;
Amount = 5000;
balance = Amount - total;

if (total > Amount) {
    JOptionPane.showMessageDialog(null, "You have insuffient funds. \n Your balance is "
            + Amount + "\n Unable to make an order of " + total + " \n Kindly Recharge your Account ", "Strathmore Cafeteria", JOptionPane.ERROR_MESSAGE);
   systemExit();
    food_drinks evans = new food_drinks();
    evans.setVisible(true);
    
}

//Allocating prices to the cost of food and cost of drinks respecctively with 2decimal places


String sub1 = String.format("%.2f", pur1);
foodcost.setText(sub1);

String sub2 = String.format("%.2f", pur2);
foodcost.setText(sub2);

String sub3 = String.format("%.2f", pur3);
foodcost.setText(sub3);

String sub4 = String.format("%.2f", pur4);
foodcost.setText(sub4);

String sub5 = String.format("%.2f", pur5);
foodcost.setText(sub5);

String sub6 = String.format("%.2f", pur6);
drinkscost.setText(sub6);

String sub7 = String.format("%.2f", pur7);
drinkscost.setText(sub7);

String sub8 = String.format("%.2f", pur8);
drinkscost.setText(sub8);

String sub9 = String.format("%.2f", pur9);
drinkscost.setText(sub9);

String sub10 = String.format("%.2f", pur10);
drinkscost.setText(sub10);

String Total = String.format("%.2f", total);
jTotal.setText(Total);

String Balance = String.format("%.2f", balance);
jBalance.setText(Balance);

//======================================================================================================================

// Generating a random receipt number
int reference_number;
reference_number = 1458+ (int) (Math.random()*5691);

// Generating the date and time to print in the  receipt.        
       int refno = reference_number;
       Calendar timer = Calendar.getInstance();
       timer.getTime();
       SimpleDateFormat t_time = new SimpleDateFormat("HH:mm:ss");
       t_time.format(timer.getTime());
       SimpleDateFormat T_date = new SimpleDateFormat("dd-MMM-yyyy");
       T_date.format(timer.getTime());
       
  // printing the receipt.
       
jtxtReceipt.append(" \t \n Strathmore Cafeteria: \n \n" 
         + "Receipt no: \t\t " + refno
         + "\n\n Item \t quantity \t Price"
         + "\n\nchips:\t " + Qty1 + "\t " + sub1
         + "\n chicken:\t " + Qty2 + "\t "+ sub2
         + "\n spagheti:\t "+ Qty3 + "\t "+ sub3
         + "\n beef: \t " + Qty4 + "\t "+ sub4
         +"\n====================================\t\t"
         + "\ncoke: \t " + Qty6 + "\t "+ sub6
         + "\nfanta: \t " + Qty7 + "\t "+ sub7
         + "\nsprite: \t " + Qty8 + "\t "+ sub8
         + "\nstoney: \t " + Qty9 +"\t "+ sub9
         +"\n====================================\t\t"
         + "\ncost of food: \t\t "+ sub5
         + "\ncost of cost of drinks: \t "+ sub10
         + "\nTotal: \t\t "+ Total
        
         +"\n====================================\t\t"
         +"\n Date: " +  T_date.format(timer.getTime())
         +"\t Time: " +   t_time.format(timer.getTime())
         +"\n\n\n Thank You for purchasing at Strathmore Cafeteria. \n\n \t Come Again \n\n\n\n\t ** evanspreeet Technology **"

);

    }//GEN-LAST:event_BtnOrderActionPerformed

    private void Price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price1ActionPerformed
          
    }//GEN-LAST:event_Price1ActionPerformed

    private food_drinks frame;
    
    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
   // Generating a dialog box when the user wants to Exit
        
        frame = new food_drinks();
        
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit", "Strathmore Cafeteria", 
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        System.exit(0);
    }
       
      systemExit();       
    
    }//GEN-LAST:event_BtnExitActionPerformed

    private void foodcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodcostActionPerformed
         
    }//GEN-LAST:event_foodcostActionPerformed

    private void jTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalActionPerformed
       
    }//GEN-LAST:event_jTotalActionPerformed
 //=====================================================================================================================
 
//Allowing only numbers to be printed in the text boxes
    
    private void jQty1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQty1KeyTyped
      
        char iNumber = evt.getKeyChar();
      if (!(Character.isDigit(iNumber)) 
          ||(iNumber == KeyEvent.VK_BACKSPACE)  
                  ||(iNumber == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jQty1KeyTyped

    private void jQty2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQty2KeyTyped
     
        char iNumber = evt.getKeyChar();
      if (!(Character.isDigit(iNumber)) 
          ||(iNumber == KeyEvent.VK_BACKSPACE)  
                  ||(iNumber == KeyEvent.VK_DELETE)){
        evt.consume();
    }

    }//GEN-LAST:event_jQty2KeyTyped

    private void jQty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQty3ActionPerformed
       
    }//GEN-LAST:event_jQty3ActionPerformed

    private void jQty3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQty3KeyTyped
 
        char iNumber = evt.getKeyChar();
      if (!(Character.isDigit(iNumber)) 
          ||(iNumber == KeyEvent.VK_BACKSPACE)  
                  ||(iNumber == KeyEvent.VK_DELETE)){
        evt.consume();
    }        
    }//GEN-LAST:event_jQty3KeyTyped

    private void jQty4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQty4KeyTyped
 
        char iNumber = evt.getKeyChar();
      if (!(Character.isDigit(iNumber)) 
          ||(iNumber == KeyEvent.VK_BACKSPACE)  
                  ||(iNumber == KeyEvent.VK_DELETE)){
        evt.consume();
    }       
    }//GEN-LAST:event_jQty4KeyTyped

    private void jQty6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQty6KeyTyped
 
        char iNumber = evt.getKeyChar();
      if (!(Character.isDigit(iNumber)) 
          ||(iNumber == KeyEvent.VK_BACKSPACE)  
                  ||(iNumber == KeyEvent.VK_DELETE)){
        evt.consume();
    }       
    }//GEN-LAST:event_jQty6KeyTyped

    private void jQty7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQty7KeyTyped
 
        char iNumber = evt.getKeyChar();
      if (!(Character.isDigit(iNumber)) 
          ||(iNumber == KeyEvent.VK_BACKSPACE)  
                  ||(iNumber == KeyEvent.VK_DELETE)){
        evt.consume();
    }        
    }//GEN-LAST:event_jQty7KeyTyped

    private void jQty8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQty8KeyTyped
 
        char iNumber = evt.getKeyChar();
      if (!(Character.isDigit(iNumber)) 
          ||(iNumber == KeyEvent.VK_BACKSPACE)  
                  ||(iNumber == KeyEvent.VK_DELETE)){
        evt.consume();
    }        
    }//GEN-LAST:event_jQty8KeyTyped

    private void jQty9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQty9KeyTyped

        char iNumber = evt.getKeyChar();
      if (!(Character.isDigit(iNumber)) 
          ||(iNumber == KeyEvent.VK_BACKSPACE)  
                  ||(iNumber == KeyEvent.VK_DELETE)){
        evt.consume();
    }        
    }//GEN-LAST:event_jQty9KeyTyped

//=====================================================================================================================================

    // Make the text field editable when the checkbox is selected
    
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        
        if (jCheckBox1.isSelected()){
            jQty1.setEnabled(true);
            jQty1.requestFocus();
            jQty1.setText("");
        }
        else {
             jQty1.setEnabled(false);
             jQty1.setText("0");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jQty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQty1ActionPerformed
       
    }//GEN-LAST:event_jQty1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
 if (jCheckBox2.isSelected()){
            jQty2.setEnabled(true);
             jQty2.requestFocus();
             jQty2.setText("");
        }
        else {
             jQty2.setEnabled(false);
              jQty2.setText("0");
        }        
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
 
        if (jCheckBox3.isSelected()){
            jQty3.setEnabled(true);
             jQty3.requestFocus();
              jQty3.setText("");
        }
        else {
             jQty3.setEnabled(false);
              jQty3.setText("0");
        }        
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
 
        if (jCheckBox4.isSelected()){
            jQty4.setEnabled(true);
             jQty4.requestFocus();
              jQty4.setText("");
        }
        else {
             jQty4.setEnabled(false);
             
              jQty4.setText("0");
        }       
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
 
        if (jCheckBox5.isSelected()){
            jQty6.setEnabled(true);
             jQty6.requestFocus();
              jQty6.setText("");
        }
        else {
             jQty6.setEnabled(false);
              jQty6.setText("0");
        }        
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
 
        if (jCheckBox6.isSelected()){
            jQty7.setEnabled(true);
             jQty7.requestFocus();
              jQty7.setText("");
        }
        else {
             jQty7.setEnabled(false);
              jQty7.setText("0");
        }       
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
 
        if (jCheckBox7.isSelected()){
            jQty8.setEnabled(true);
             jQty8.requestFocus();
              jQty8.setText("");
        }
        else {
             jQty8.setEnabled(false);
              jQty8.setText("0");
        }        
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
 
        if (jCheckBox8.isSelected()){
            jQty9.setEnabled(true);
             jQty9.requestFocus();
              jQty9.setText("");
        }
        else {
             jQty9.setEnabled(false);
              jQty9.setText("0");
        }        
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void Price2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Price2KeyTyped

        if (jCheckBox2.isSelected()){
            Price2.setEnabled(false);
        }
        else {
             jQty2.setEnabled(false);
        }
                
    }//GEN-LAST:event_Price2KeyTyped

    //=========================================================================================================================================
    
    private void Price2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price2ActionPerformed

    }//GEN-LAST:event_Price2ActionPerformed

    //setting the prices when mouse is moved.
    
    private void Price1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Price1MouseMoved
Price1.setText("100");       
    }//GEN-LAST:event_Price1MouseMoved

    private void Price2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Price2MouseMoved
Price2.setText("120");       
    }//GEN-LAST:event_Price2MouseMoved

    private void Price3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Price3MouseMoved
Price3.setText("90");       
    }//GEN-LAST:event_Price3MouseMoved

    private void Price4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Price4MouseMoved
Price4.setText("150");        
    }//GEN-LAST:event_Price4MouseMoved

    private void Price6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Price6MouseMoved
Price6.setText("50");       
    }//GEN-LAST:event_Price6MouseMoved

    private void Price7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Price7MouseMoved
Price7.setText("50");       
    }//GEN-LAST:event_Price7MouseMoved

    private void Price8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Price8MouseMoved
Price8.setText("50");        
    }//GEN-LAST:event_Price8MouseMoved

    private void Price9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Price9MouseMoved
Price9.setText("50");        
    }//GEN-LAST:event_Price9MouseMoved

    private void jBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBalanceMouseClicked
      
    }//GEN-LAST:event_jBalanceMouseClicked

    private void jBalanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBalanceMousePressed
      // TODO add your handling code here:
    }//GEN-LAST:event_jBalanceMousePressed

    //=========================================================================================================================================
    //Main method
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new food_drinks().setVisible(true);
            }
        });
    }
//=============================================================================================================================================
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnOrder;
    private javax.swing.JButton BtnReceipt;
    private javax.swing.JButton BtnReset;
    private javax.swing.JTextField Price1;
    private javax.swing.JTextField Price2;
    private javax.swing.JTextField Price3;
    private javax.swing.JTextField Price4;
    private javax.swing.JTextField Price6;
    private javax.swing.JTextField Price7;
    private javax.swing.JTextField Price8;
    private javax.swing.JTextField Price9;
    private javax.swing.JTextField drinkscost;
    private javax.swing.JTextField foodcost;
    private javax.swing.JTextField jBalance;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jQty1;
    private javax.swing.JTextField jQty2;
    private javax.swing.JTextField jQty3;
    private javax.swing.JTextField jQty4;
    private javax.swing.JTextField jQty6;
    private javax.swing.JTextField jQty7;
    private javax.swing.JTextField jQty8;
    private javax.swing.JTextField jQty9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTotal;
    private javax.swing.JTextArea jtxtReceipt;
    // End of variables declaration//GEN-END:variables
}
